language: julia

os:
  - linux

julia:
  - 1.1
  - 1.5
  - nightly

jobs:
  allow_failures:
    - julia: nightly

  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
